; sprite ids
; OverworldSprites indexes (see data/sprites/sprites.asm)
	const_def
	const SPRITE_NONE ; 00
	const SPRITE_CHRIS ; 01
	const SPRITE_CHRIS_BIKE ; 02
	const SPRITE_GAMEBOY_KID ; 03
	const SPRITE_SILVER ; 04
	const SPRITE_OAK ; 05
	const SPRITE_RED ; 06
	const SPRITE_BLUE ; 07
	const SPRITE_BILL ; 08
	const SPRITE_ELDER ; 09
	const SPRITE_JANINE ; 0a
	const SPRITE_KURT ; 0b
	const SPRITE_MOM ; 0c
	const SPRITE_BLAINE ; 0d
	const SPRITE_REDS_MOM ; 0e
	const SPRITE_DAISY ; 0f
	const SPRITE_ELM ; 10
	const SPRITE_WILL ; 11
	const SPRITE_FALKNER ; 12
	const SPRITE_WHITNEY ; 13
	const SPRITE_BUGSY ; 14
	const SPRITE_MORTY ; 15
	const SPRITE_CHUCK ; 16
	const SPRITE_JASMINE ; 17
	const SPRITE_PRYCE ; 18
	const SPRITE_CLAIR ; 19
	const SPRITE_BROCK ; 1a
	const SPRITE_KAREN ; 1b
	const SPRITE_BRUNO ; 1c
	const SPRITE_MISTY ; 1d
	const SPRITE_LANCE ; 1e
	const SPRITE_SURGE ; 1f
	const SPRITE_ERIKA ; 20
	const SPRITE_KOGA ; 21
	const SPRITE_SABRINA ; 22
	const SPRITE_COOLTRAINER_M ; 23
	const SPRITE_COOLTRAINER_F ; 24
	const SPRITE_BUG_CATCHER ; 25
	const SPRITE_TWIN ; 26
	const SPRITE_YOUNGSTER ; 27
	const SPRITE_LASS ; 28
	const SPRITE_TEACHER ; 29
	const SPRITE_BEAUTY ; 2a
	const SPRITE_SUPER_NERD ; 2b
	const SPRITE_ROCKER ; 2c
	const SPRITE_POKEFAN_M ; 2d
	const SPRITE_POKEFAN_F ; 2e
	const SPRITE_GRAMPS ; 2f
	const SPRITE_GRANNY ; 30
	const SPRITE_SWIMMER_GUY ; 31
	const SPRITE_SWIMMER_GIRL ; 32
	const SPRITE_BIG_SNORLAX ; 33
	const SPRITE_SURFING_PIKACHU ; 34
	const SPRITE_ROCKET ; 35
	const SPRITE_ROCKET_GIRL ; 36
	const SPRITE_NURSE ; 37
	const SPRITE_LINK_RECEPTIONIST ; 38
	const SPRITE_CLERK ; 39
	const SPRITE_FISHER ; 3a
	const SPRITE_FISHING_GURU ; 3b
	const SPRITE_SCIENTIST ; 3c
	const SPRITE_KIMONO_GIRL ; 3d
	const SPRITE_SAGE ; 3e
	const SPRITE_UNUSED_GUY ; 3f
	const SPRITE_GENTLEMAN ; 40
	const SPRITE_BLACK_BELT ; 41
	const SPRITE_RECEPTIONIST ; 42
	const SPRITE_OFFICER ; 43
	const SPRITE_CAL ; 44
	const SPRITE_SLOWPOKE ; 45
	const SPRITE_CAPTAIN ; 46
	const SPRITE_BIG_LAPRAS ; 47
	const SPRITE_GYM_GUIDE ; 48
	const SPRITE_SAILOR ; 49
	const SPRITE_BIKER ; 4a
	const SPRITE_PHARMACIST ; 4b
	const SPRITE_MONSTER ; 4c
	const SPRITE_FAIRY ; 4d
	const SPRITE_BIRD ; 4e
	const SPRITE_DRAGON ; 4f
	const SPRITE_BIG_ONIX ; 50
	const SPRITE_N64 ; 51
	const SPRITE_SUDOWOODO ; 52
	const SPRITE_SURF ; 53
	const SPRITE_POKE_BALL ; 54
	const SPRITE_POKEDEX ; 55
	const SPRITE_PAPER ; 56
	const SPRITE_VIRTUAL_BOY ; 57
	const SPRITE_OLD_LINK_RECEPTIONIST ; 58
	const SPRITE_ROCK ; 59
	const SPRITE_BOULDER ; 5a
	const SPRITE_SNES ; 5b
	const SPRITE_FAMICOM ; 5c
	const SPRITE_FRUIT_TREE ; 5d
	const SPRITE_GOLD_TROPHY ; 5e
	const SPRITE_SILVER_TROPHY ; 5f
	const SPRITE_KRIS ; 60
	const SPRITE_KRIS_BIKE ; 61
	const SPRITE_KURT_OUTSIDE ; 62
	const SPRITE_SUICUNE ; 63
	const SPRITE_ENTEI ; 64
	const SPRITE_RAIKOU ; 65
	const SPRITE_STANDING_YOUNGSTER ; 66

; SpriteMons indexes (see data/sprites/sprite_mons.asm)
	const_next $80
SPRITE_POKEMON EQU const_value
	const _SPRITE_BULBASAUR
	const _SPRITE_IVYSAUR
	const _SPRITE_VENUSAUR
	const _SPRITE_CHARMANDER
	const _SPRITE_CHARMELEON
	const _SPRITE_CHARIZARD
	const _SPRITE_SQUIRTLE
	const _SPRITE_WARTORTLE
	const _SPRITE_BLASTOISE
	const _SPRITE_CATERPIE
	const _SPRITE_METAPOD
	const _SPRITE_BUTTERFREE
	const _SPRITE_WEEDLE
	const _SPRITE_KAKUNA
	const _SPRITE_BEEDRILL
	const _SPRITE_PIDGEY
	const _SPRITE_PIDGEOTTO
	const _SPRITE_PIDGEOT
	const _SPRITE_RATTATA
	const _SPRITE_RATICATE
	const _SPRITE_SPEAROW
	const _SPRITE_FEAROW
	const _SPRITE_EKANS
	const _SPRITE_ARBOK
	const _SPRITE_PIKACHU
	const _SPRITE_RAICHU
	const _SPRITE_SANDSHREW
	const _SPRITE_SANDSLASH
	const _SPRITE_NIDORAN_F
	const _SPRITE_NIDORINA
	const _SPRITE_NIDOQUEEN
	const _SPRITE_NIDORAN_M
	const _SPRITE_NIDORINO
	const _SPRITE_NIDOKING
	const _SPRITE_CLEFAIRY
	const _SPRITE_CLEFABLE
	const _SPRITE_VULPIX
	const _SPRITE_NINETALES
	const _SPRITE_JIGGLYPUFF
	const _SPRITE_WIGGLYTUFF
	const _SPRITE_ZUBAT
	const _SPRITE_GOLBAT
	const _SPRITE_ODDISH
	const _SPRITE_GLOOM
	const _SPRITE_VILEPLUME
	const _SPRITE_PARAS
	const _SPRITE_PARASECT
	const _SPRITE_VENONAT
	const _SPRITE_VENOMOTH
	const _SPRITE_DIGLETT
	const _SPRITE_DUGTRIO
	const _SPRITE_MEOWTH
	const _SPRITE_PERSIAN
	const _SPRITE_PSYDUCK
	const _SPRITE_GOLDUCK
	const _SPRITE_MANKEY
	const _SPRITE_PRIMEAPE
	const _SPRITE_GROWLITHE
	const _SPRITE_ARCANINE
	const _SPRITE_POLIWAG
	const _SPRITE_POLIWHIRL
	const _SPRITE_POLIWRATH
	const _SPRITE_ABRA
	const _SPRITE_KADABRA
	const _SPRITE_ALAKAZAM
	const _SPRITE_MACHOP
	const _SPRITE_MACHOKE
	const _SPRITE_MACHAMP
	const _SPRITE_BELLSPROUT
	const _SPRITE_WEEPINBELL
	const _SPRITE_VICTREEBEL
	const _SPRITE_TENTACOOL
	const _SPRITE_TENTACRUEL
	const _SPRITE_GEODUDE
	const _SPRITE_GRAVELER
	const _SPRITE_GOLEM
	const _SPRITE_PONYTA
	const _SPRITE_RAPIDASH
	const _SPRITE_SLOWPOKE
	const _SPRITE_SLOWBRO
	const _SPRITE_MAGNEMITE
	const _SPRITE_MAGNETON
	const _SPRITE_FARFETCH_D
	const _SPRITE_DODUO
	const _SPRITE_DODRIO
	const _SPRITE_SEEL
	const _SPRITE_DEWGONG
	const _SPRITE_GRIMER
	const _SPRITE_MUK
	const _SPRITE_SHELLDER
	const _SPRITE_CLOYSTER
	const _SPRITE_GASTLY
	const _SPRITE_HAUNTER
	const _SPRITE_GENGAR
	const _SPRITE_ONIX
	const _SPRITE_DROWZEE
	const _SPRITE_HYPNO
	const _SPRITE_KRABBY
	const _SPRITE_KINGLER
	const _SPRITE_VOLTORB
	const _SPRITE_ELECTRODE
	const _SPRITE_EXEGGCUTE
	const _SPRITE_EXEGGUTOR
	const _SPRITE_CUBONE
	const _SPRITE_MAROWAK
	const _SPRITE_HITMONLEE
	const _SPRITE_HITMONCHAN
	const _SPRITE_LICKITUNG
	const _SPRITE_KOFFING
	const _SPRITE_WEEZING
	const _SPRITE_RHYHORN
	const _SPRITE_RHYDON
	const _SPRITE_CHANSEY
	const _SPRITE_TANGELA
	const _SPRITE_KANGASKHAN
	const _SPRITE_HORSEA
	const _SPRITE_SEADRA
	const _SPRITE_GOLDEEN
	const _SPRITE_SEAKING
	const _SPRITE_STARYU
	const _SPRITE_STARMIE
	const _SPRITE_MR_MIME
	const _SPRITE_SCYTHER
	const _SPRITE_JYNX
	const _SPRITE_ELECTABUZZ
	const _SPRITE_MAGMAR
	const _SPRITE_PINSIR
	const _SPRITE_TAUROS
	const _SPRITE_MAGIKARP
	const _SPRITE_GYARADOS
	const _SPRITE_LAPRAS
	const _SPRITE_DITTO
	const _SPRITE_EEVEE
	const _SPRITE_VAPOREON
	const _SPRITE_JOLTEON
	const _SPRITE_FLAREON
	const _SPRITE_PORYGON
	const _SPRITE_OMANYTE
	const _SPRITE_OMASTAR
	const _SPRITE_KABUTO
	const _SPRITE_KABUTOPS
	const _SPRITE_AERODACTYL
	const _SPRITE_SNORLAX
	const _SPRITE_ARTICUNO
	const _SPRITE_ZAPDOS
	const _SPRITE_MOLTRES
	const _SPRITE_DRATINI
	const _SPRITE_DRAGONAIR
	const _SPRITE_DRAGONITE
	const _SPRITE_MEWTWO
	const _SPRITE_MEW
	const _SPRITE_CHIKORITA
	const _SPRITE_BAYLEEF
	const _SPRITE_MEGANIUM
	const _SPRITE_CYNDAQUIL
	const _SPRITE_QUILAVA
	const _SPRITE_TYPHLOSION
	const _SPRITE_TOTODILE
	const _SPRITE_CROCONAW
	const _SPRITE_FERALIGATR
	const _SPRITE_SENTRET
	const _SPRITE_FURRET
	const _SPRITE_HOOTHOOT
	const _SPRITE_NOCTOWL
	const _SPRITE_LEDYBA
	const _SPRITE_LEDIAN
	const _SPRITE_SPINARAK
	const _SPRITE_ARIADOS
	const _SPRITE_CROBAT
	const _SPRITE_CHINCHOU
	const _SPRITE_LANTURN
	const _SPRITE_PICHU
	const _SPRITE_CLEFFA
	const _SPRITE_IGGLYBUFF
	const _SPRITE_TOGEPI
	const _SPRITE_TOGETIC
	const _SPRITE_NATU
	const _SPRITE_XATU
	const _SPRITE_MAREEP
	const _SPRITE_FLAAFFY
	const _SPRITE_AMPHAROS
	const _SPRITE_BELLOSSOM
	const _SPRITE_MARILL
	const _SPRITE_AZUMARILL
	const _SPRITE_SUDOWOODO
	const _SPRITE_POLITOED
	const _SPRITE_HOPPIP
	const _SPRITE_SKIPLOOM
	const _SPRITE_JUMPLUFF
	const _SPRITE_AIPOM
	const _SPRITE_SUNKERN
	const _SPRITE_SUNFLORA
	const _SPRITE_YANMA
	const _SPRITE_WOOPER
	const _SPRITE_QUAGSIRE
	const _SPRITE_ESPEON
	const _SPRITE_UMBREON
	const _SPRITE_MURKROW
	const _SPRITE_SLOWKING
	const _SPRITE_MISDREAVUS
	const _SPRITE_UNOWN
	const _SPRITE_WOBBUFFET
	const _SPRITE_GIRAFARIG
	const _SPRITE_PINECO
	const _SPRITE_FORRETRESS
	const _SPRITE_DUNSPARCE
	const _SPRITE_GLIGAR
	const _SPRITE_STEELIX
	const _SPRITE_SNUBBULL
	const _SPRITE_GRANBULL
	const _SPRITE_QWILFISH
	const _SPRITE_SCIZOR
	const _SPRITE_SHUCKLE
	const _SPRITE_HERACROSS
	const _SPRITE_SNEASEL
	const _SPRITE_TEDDIURSA
	const _SPRITE_URSARING
	const _SPRITE_SLUGMA
	const _SPRITE_MAGCARGO
	const _SPRITE_SWINUB
	const _SPRITE_PILOSWINE
	const _SPRITE_CORSOLA
	const _SPRITE_REMORAID
	const _SPRITE_OCTILLERY
	const _SPRITE_DELIBIRD
	const _SPRITE_MANTINE
	const _SPRITE_SKARMORY
	const _SPRITE_HOUNDOUR
	const _SPRITE_HOUNDOOM
	const _SPRITE_KINGDRA
	const _SPRITE_PHANPY
	const _SPRITE_DONPHAN
	const _SPRITE_PORYGON2
	const _SPRITE_STANTLER
	const _SPRITE_SMEARGLE
	const _SPRITE_TYROGUE
	const _SPRITE_HITMONTOP
	const _SPRITE_SMOOCHUM
	const _SPRITE_ELEKID
	const _SPRITE_MAGBY
	const _SPRITE_MILTANK
	const _SPRITE_BLISSEY
	const _SPRITE_RAIKOU
	const _SPRITE_ENTEI
	const _SPRITE_SUICUNE
	const _SPRITE_LARVITAR
	const _SPRITE_PUPITAR
	const _SPRITE_TYRANITAR
	const _SPRITE_LUGIA
	const _SPRITE_HO_OH
	const _SPRITE_CELEBI
	const _SPRITE_EGG

; special GetMonSprite values (see engine/overworld/overworld.asm)
	const_next $e0
	const SPRITE_DAY_CARE_MON_1 ; e0
	const SPRITE_DAY_CARE_MON_2 ; e1

; wVariableSprites indexes (see wram.asm)
	const_next $f0
SPRITE_VARS EQU const_value
	const SPRITE_CONSOLE ; f0
	const SPRITE_DOLL_1 ; f1
	const SPRITE_DOLL_2 ; f2
	const SPRITE_BIG_DOLL ; f3
	const SPRITE_WEIRD_TREE ; f4
	const SPRITE_OLIVINE_RIVAL ; f5
	const SPRITE_AZALEA_ROCKET ; f6
	const SPRITE_FUCHSIA_GYM_1 ; f7
	const SPRITE_FUCHSIA_GYM_2 ; f8
	const SPRITE_FUCHSIA_GYM_3 ; f9
	const SPRITE_FUCHSIA_GYM_4 ; fa
	const SPRITE_COPYCAT ; fb
	const SPRITE_JANINE_IMPERSONATOR ; fc
